#165177754 fix confirmation eamil
andela/apollo-ah-backend pull request #61
Opened 2019-04-08 11:15 UTC by davdwhyte87

#### What does this PR do?
This PR changes the link sent to users on registration to a link pointing to the front-end

#### Description of Task to be completed?
- fix confirmation link to point to a front end app

#### How should this be manually tested?
- clone the repo
- install postgress, node js and yarn
- run yarn install to install dependencies
- run yarn start:dev
- create a new user and you should receive an email with a link that points to a site configured on the .env file (WEB_APP)

#### What are the relevant pivotal tracker stories?
`165177754`

2019-04-08 12:00 UTC, thislekan commented on server/controllers/usersController.js
> +      const confrimLink = `${env('WEB_APP')}?token=${confirmToken}`;
Well done, @davdwhyte87 

There's a typo here. Also, we can use the variable names: confirmationLink and confirmationToken instead.

2019-04-08 12:01 UTC, thislekan requested changes
Please see the comments and make the changes

2019-04-08 13:51 UTC, thislekan approved these changes

2019-04-09 00:26 UTC, aanchirinah approved these changes
LGTM

2019-04-09 10:09 UTC, merged