#165344089 Implement clapping functionality
andela/apollo-ah-backend pull request #65
Opened 2019-04-21 00:36 UTC by devdbrandy

#### What does this PR do?

This provides support for adding claps to articles

#### Description of Task to be completed?

- [x] Introduce new endpoint `POST /articles/{slug}/claps` - Add/update claps to specific article
   Request body - `claps` number of claps
- [x] Introduce new endpoint `GET /articles/{slug}/claps` - Get article claps
- [x] Add migration for article claps
- [x] Add `ArticleClaps` model
- [x] Add endpoint for creating/update an article claps
- [x] Write test against implementation
- [x] Add validation for allowed number of claps

#### How should this be manually tested?

1. Run the following commands on terminal:

```bash
git clone -b feature/165344089/clapping-functionality --single-branch \
https://github.com/andela/apollo-ah-backend.git

cd apollo-ah-backend
cp .env.example .env

# To run test
cp .env.example .env.test

# Install package modules
npm install
```

2. Modify `.env` file with your db credentials

3. Run database migrations with `npm run migrate`

4. Run seeders with `npm run seed`

5. Spin up the server by running `npm run start:dev` on your terminal

6. Test new endpoints listed above ☝️with [Postman](https://www.getpostman.com/downloads/).

#### Running test locally

Two npm scripts are available to run the test suite:

- `npm run mocha` or `npm run mocha:watch` - The later watches for any file changes and runs the full test suite (without code coverage)
- `npm test` - Performs a single full test suite run, including Istanbul code coverage reporting. Summary coverage reports are written to stdout, and detailed HTML reports are available in /coverage/index.html

**NOTE:** To run test locally, make sure to create `.env.test` file.

#### Any background context you want to provide?

n/a

#### What are the relevant pivotal tracker stories?

[#165344089](https://www.pivotaltracker.com/story/show/165344089)

#### Screenshots (if appropriate)

n/a

2019-04-21 06:09 UTC, valenstical requested changes
This is really good work @devdbrandy, we now have a clapping functionality. 
I have just a few requested changes. Good work once more.

2019-04-21 06:09 UTC, valenstical commented on server/controllers/clapsController.js
> +      const article = await models.Article.findOne({ where: { slug } });
~~Do you think we can move this validation to a middleware?~~

2019-04-21 06:09 UTC, valenstical commented on test/integrations/routes/claps.test.js
> +        .set({ Authorization: `Bearer ${userToken}` })
_Hmmmm_, this means, I must be logged in to view claps for a specific article. 
 Do you think it would also be OK for unauthorized users to view the number of claps for a specific article? Since this is not really a secret. 😊

2019-04-21 06:09 UTC, valenstical commented on test/integrations/routes/claps.test.js
> +    it('Should throw validation error when claps exceeds 100', (done) => {
Can we also add validation test for when the clap parameter is not supplied or it's not a number?

2019-04-21 06:09 UTC, valenstical commented on server/middlewares/validator.js
> +        .withMessage('Claps must not exceed 100'),
Would you consider adding a different validation to check if the clap parameter is an integer (or it's empty as well). 
With the current implementation, users will get the message '_Claps must not exceed 100_' if they enter

- An invalid number
- The clap parameter is not supplied

2019-04-22 02:39 UTC, aanchirinah approved these changes
LGTM

2019-04-22 13:06 UTC, valenstical approved these changes
LGTM

2019-04-22 17:04 UTC, devdbrandy commented on test/integrations/routes/claps.test.js
> +        .set({ Authorization: `Bearer ${userToken}` })
Thats a good point @valenstical, thanks for pointing that. 
However, the idea behind this is to have an interface where both authenticated users and authors can get a list of claps and by who. Regarding the number claps, we already have that included as part of result obtained when fetching article resource(s).

2019-04-22 19:29 UTC, devdbrandy commented on test/integrations/routes/claps.test.js
> +    it('Should throw validation error when claps exceeds 100', (done) => {
Thanks for pointing that, I've implemented the requested changes.

2019-04-26 04:20 UTC, merged